vaticle/typedb-common

WORKSPACE, config/rpm/grakn-bin.spec
Newest changes in `bazel-distribution` (graknlabs/bazel-distribution#181) are backwards-incompatible.
- Uses workspace macros from most recent `bazel-distribution` version
=> Adapt to latest @graknlabs_bazel_distribution

.circleci/config.yml, BUILD, bin/BUILD
Adapt `@graknlabs_common` to latest changes in bazel-distribution (in particular, graknlabs/bazel-distribution#150)
Instead of supplying `version_file` everywhere, use `--define version=<>` as a Bazel argument to supply version.
=> Refactor how version is provided to deployment rules

util/Collections.java, util/Pair.java, util/Triple.java
Change the package `util` to be `grakn.core.util` to reflect the common naming scheme across Grakn packages.
=> Change package definitions

BUILD, WORKSPACE, dependencies/graknlabs/repositories.bzl
Following the implemation of https://github.com/graknlabs/bazel-distribution/pull/248, we can directly depend on `bazel_distribution` for `assemble-maven` and `deploy-maven` rules, and no longer use `graknlabs_dependencies` for this.
* use new implemetatnion of `assemble-maven` with argument for maven overrides
=> Assemble maven from bazel_distribution

binary/grakn
Fix #29
Currently, starting Grakn Server (or Grakn Console) starts *two* processes (`zsh` is the shell from where you've unpacked Grakn and starting it):
```
PID TTY          TIME CMD
114591 pts/0    00:00:02 zsh
164980 pts/0    00:00:00  \_ bash
164996 pts/0    00:00:02  |   \_ java
```
This PR makes Grakn the real foreground process:
```
PID TTY          TIME CMD
114591 pts/0    00:00:02 zsh
165363 pts/0    00:00:02  \_ java
```
This prevents the situation where you do `./grakn server &`, kill the process but Grakn continues running.
Prefix spawning `java` process with `exec` so it replaces the script it is in.
=> Fix Grakn execution script

.github/CODEOWNERS, binary/grakn, binary/grakn.bat
To give users (and ourselves!) a convenient way of running Grakn in debug mode, where Grakn and RocksDB assertions are enabled.
Add debug mode to Grakn executable (shell only, so not Windows).
=> Add debug mode to Grakn executable (shell only)

binary/grakn, dependencies/graknlabs/repositories.bzl
To fix Grakn failing to start in Linux.
Move the directive `#!/usr/bin/env bash` to line 1 of `grakn`. Linux ignores it if it's not on line 1.
=> Fix Grakn failing to start in Linux

binary/grakn
To allow Grakn to look at command line arguments such as --port
Fix Grakn ignoring all command line args in the executable
=> Fix Grakn ignoring all command line arguments

concurrent/actor/Actor.java, concurrent/actor/ActorPeriodicTask.java, concurrent/actor/ActorRoot.java, concurrent/actor/BUILD, concurrent/actor/eventloop/EventLoop.java, concurrent/actor/eventloop/EventLoopSingleThreaded.java, concurrent/actor/eventloop/EventLoopThreadChecker.java, concurrent/actor/eventloop/GlobalSystem.java, concurrent/actor/eventloop/LogicalTimerQueue.java, concurrent/actor/eventloop/Promise.java, concurrent/actor/test/ActorTest.java, concurrent/actor/test/BUILD, concurrent/actor/test/EventLoopTest.java, concurrent/actor/testkit/BUILD, concurrent/actor/testkit/TestState.java
We've introduced the `Actor` concurrency model library. The library will be located under `//concurrent/actor`.
Here's an example of how to create an actor that keeps track of a counter, which can be incremented in a thread-safe way by multiple threads.
```
// Counter.java
public class Counter extends Actor.State<Counter> {
int count = 0;
public Counter(Actor<Counter> self) {
super(self);
}
public void increment() {
count++;
System.out.println("current count: " + count);
}
}
// Main.java
public void main() {
EventLoopSingleThreaded eventLoop = new EventLoopSingleThreaded(NamedThreadFactory.create(GraknServer.class, "main"));
Actor<ActorRoot> rootActor = Actor.root(eventLoop, ActorRoot::new);
Actor<Counter> counterActor = rootActor.ask(root -> …
```
=> Add Actor model

concurrent/NamedThreadFactory.java
In cluster, we need to create thread factory with prefix based on functionality instead of class name and function. E.g. we want `event-loop::0`, `client-rpc::1` and so on.
Add a constructor to `NamedThreadFactory` to allow providing an arbitrary prefix.
=> Extend NamedThreadFactory with arbitrary prefix

binary/grakn
Currently there's an off by one bug which causes that `console` (when you run `./grakn console ...`) be thought as the first argument to grakn console.
=> Fix console argument off by one bug

test/server/GraknCoreRunner.java, test/server/rules.bzl
To allow client-java tests to automatically extract a Grakn Core archive native to the host platform when run.
Previously, they would not - you were stuck with whichever artifact was configured in client-java's `artifacts.bzl`, which was `grakn-core-server-linux`. This would fail to run on a Mac machine.
- Add a `genrule` to `grakn_java_test` that selectively copies the platform-native Grakn artifact to a fixed filename, `grakn-core-server-native.tar.gz`
- Update GraknCoreRunner to specify a fixed folder name to unzip the artifact to, then find the Grakn executable by `cd`-ing to the first folder inside the directory. This isn't ideal, but it works because our Grakn archive contains a single root directory. (Its name varies with the platform and version)
=> Allow grakn_java_test to choose a platform-native Grakn artifact

test/server/GraknCoreRunner.java
To stabilise the flaky client-java tests.
One of the issues is that Grakn can take up to 9 seconds to start. This causes entire test suites to fail with errors.
Wait a bit longer for Grakn to start when running Java tests (changed from 5 seconds to 10 seconds)
=> Wait a bit longer for Grakn to start when testing

collection/Bytes.java, collection/Collections.java
Clarify unmodifiable collections helpers to avoid clashing types. We rename them to both avoid clashing types and make their intention clearer.
* Rename util methods
* Remove `final` in arguments
=> Update collections utils to avoid clashing parameters

binary/BUILD
Grakn 2.0 uses a different directory for logs, therefore path for `grakn-bin` APT package needs to be adjusted, relevant config entry is [here](https://github.com/graknlabs/grakn-2.0/blob/e63aa72cc45ba830c9b15b02c760555c40dddd2c/server/conf/grakn.properties#L22).
Adjust package of where logs are stored for APT package
=> //binary:assemble-linux-apt: adjust path to log dir for Grakn 2.0

test/server/logback.xml, test/server/rules.bzl
To fix client-java being unable to build in Grabl (failing >70% of the time) due to excess network usage.
We separate out `native_grakn_artifact` so it is no longer defined as part of `grakn_java_test`. Instead, the user is now required to declare a `native_grakn_artifact` in their project, if they want to use it for their `grakn_java_test`s.
As a result, the Grakn artifact ends up being declared in one place and one place only. This is good both on a conceptual level, and practically, because BuildBuddy was uploading the output of every declared Bazel target to a remote server. Given that we have about 32 `grakn_java_test`s in client-java, this meant uploading Grakn 32 times. It is 160MB including both the Linux and Mac distributions, so this was a pretty big hit. It actually made the …
=> Fix Grakn artifact getting fetched many times when building client

test/server/rules.bzl
As we need to test Grakn on Windows, `native_grakn_artifact` needs to support it.
Allow passing `windows_artifact` to `native_grakn_artifact` and pass if further to `genrule`
=> Support native_grakn_artifact for Windows

WORKSPACE, dependencies/graknlabs/repositories.bzl, dependencies/maven/artifacts.snapshot
Currently, `dependency-analysis` job fails to run `@graknlabs_dependencies//grabl/analysis:dependency-analysis` which happened because of a missing dependency. This is fixed in this PR and graknlabs/dependencies#233
* Upgrade `@graknlabs_dependencies` to current latest `master`
* Load Maven dependencies of `@graknlabs_dependencies//grabl/analysis:dependency-analysis`
=> Upgrade @graknlabs_dependencies to fix dependency-analysis

concurrent/actor/Actor.java, concurrent/actor/EventLoop.java
We have fixed the issue where a race condition may occur when submitting a scheduled job onto the EventLoop.
The race condition is caused by the fact we are returning a reference to a `Cancellable` which may not yet have been created.
The solution is to redesign `Cancellable` such that it can be immediately constructed.
Closes https://github.com/graknlabs/common/issues/66
=> Fix a the issue where you may get back a null Cancellable from an EventLoop

binary/grakn, binary/grakn.bat, test/server/GraknCoreRunner.java, test/server/rules.bzl
Fix the testing infrastructure to allow testing Grakn Core distribution under Windows.
* `grakn_java_test` rule macro no longer accepts `select` and instead takes in the native artifact mapping in this form:
```
grakn_java_test(
mac_artifact = "//server:assemble-mac-zip",
linux_artifact =  "//server:assemble-linux-targz",
windows_artifact = "//server:assemble-windows-zip",
}
```
This allows to pass the correct platform-specific artifact and preserve its extension to the test (previously they would all end up under fixed name of `grakn-core-native-artifact.tar.gz`, for Linux, Windows and Mac artifacts making it impossible for `GraknCoreRunner` to tell for which distribution is the artifact for)
More about this implementation of this approach …
=> Fix testing rules and runner to work under Windows

test/server/GraknRunnerBase.java
Fix tests that depend on `GraknCoreRunner`.
Resolve data directory against the unpacked distrubution directory
=> Resolve data directory in GraknRunnerBase after distribution has been unpacked

binary/grakn
Fix an issue causing grakn startup script to disregard the debug mode parameter.
- Use the correct shell parameter expansion to check only a single argument, instead of all remaining arguments. Otherwise `./grakn server --debug --port 1729` will not be considered to be in the debug mode, whereas `./grakn server --debug` will be.
=> Fix debug mode in grakn start up script

binary/grakn
Fix Grakn startup script so that it can run with debug flag on Linux, which will fallback to using production version and gives you a warning.
- Since RocksDB dev jar only works on Mac, we disable it on Linux.
=> Fix grakn debug mode in linux

test/server/GraknRunnerBase.java
Previously we waited N milliseconds and then ran the tests. This was wasteful, because often Grakn would start way in advance; and unreliable, because sometimes Grakn would not start in time and CI would fail. Now, we add a polling loop that checks if the server port is in use, and signals that the tests may begin once the port is in use.
- When setting up tests that use a background Grakn server, poll the used ports every 500ms to detect when Grakn is alive, and then run the tests
=> When running tests, poll used ports to identify when Grakn starts

test/server/GraknRunner.java
Fix bug in waiting for server start and stopping server.
- Use the correct `lsof` command to only list listening ports and not converting ports to names.
- Force shutdown server so that we are sure that the server is stopped after the `stop()` returns.
=> Fix bug in waiting for server start and stopping server

test/server/GraknClusterRunner.java
We fixed a bug where our tests were failing in Cluster because they started up Cluster with invalid port numbers outside the legal range.
Fix Grakn Cluster runner using invalid ports
=> Fix Grakn Cluster runner using invalid ports

test/Runner.java, test/server/GraknRunner.java
Fix failing `test-assembly-windows-zip` CI job in Core
* Use temporary directory for unpacking Grakn distribution
* Use a portable way to check if Grakn port is already being listened on
=> Fixes for Grakn Core assembly test to not fail under Windows

test/server/GraknClusterRunner.java
We've updated`GraknClusterRunner` to reflect the new way that peers are specified.
1. Change the way peers are specified, from this: `--peers=peer1,peer2,peer3` to this: `--peer peer1 --peer peer2 --peer peer3`.
=> Update the way peers are specified in GraknClusterRunner

binary/grakn.bat
Don't print license header when executing `grakn.bat` under Windows
Add `@echo off` such that `cmd.exe` doesn't print out `REM` lines containing license header
=> Fix ASCII header on Windows

binary/grakn, binary/grakn.bat
Improve consistency of Grakn Console distribution and help fix an issue with long filenames in the assembled archives.
Move console libraries into `console/lib/`
=> Tweak location of console libraries

binary/BUILD, binary/grakn-core.service
Allow daemonizing Grakn Core on systemd-based Linux systems which helps with operating production deployments.
Implement `grakn-core.service` and package it with `grakn-core-bin` APT package
Fix graknlabs/grakn#3315
=> Add SystemD service for Grakn Core

binary/typedb
We have added support for running a TypeDB Cluster node from the binary script:
```
$ ./typedb node
```
Additionally, we did a minor refactor simplifying how a user can specify `JAVAOPTS`:
```
JAVAOPTS=... ./typedb server
JAVAOPTS=... ./typedb node
JAVAOPTS=... ./typedb console
```
Last but not least, we fixed a bug where a user can execute an obsolete command `./typedb version`. The right command for checking the server version is `./typedb server --version`.
1. Added support for running a TypeDB Cluster node
- Make the logic for running Server and Node generic
- Initialised Server and Node configurations with different value
2. Minor refactor: `CONSOLE_JAVAOPTS` and `SERVER_JAVAOPTS` environment variables have been renamed to `JAVAOPTS`.
3. Removed an obsolete command `./typedb version` …
=> Add the 'typedb node' option for running a TypeDB Cluster Node

test/server/TypeDBClusterRunner.java, test/server/TypeDBCoreRunner.java, test/server/TypeDBRunner.java
We've improved TypeDBRunner logs and assertions, in order to provide a better troubleshooting / debugging experience for developers.
- TypeDBRunner instance will first check if the ports are used before starting
- TypeDBRunner instance will print the address in the logs whenever possible. This is especially useful in TypeDBClusterRunner where there may be multiple instances running at the same time.
- Fix a bug where the log file isn't displayed due to using an incorrect relative path
=> Improve TypeDBRunner logs and assertions

binary/typedb
We've added the support for running TypeBD and TypeDB Cluster using the command `./typedb server` and `./typedb cluster`, respectively.
1. Add the command `./typedb cluster` and additionally adds a check which throws an error, if executed on a TypeDB instead of a TypeDB Cluster distribution
2. Adds a check to the `./typedb server`, which throws an error if executed on a TypeDB Cluster instead of TypeDB distribution
=> Supports running TypeDB Cluster

binary/typedb.bat
User can now boot up TypeDB Cluster on Windows with `./typedb.bat cluster`
Handle `cluster` argument in `typedb.bat`
Fix #111
=> 'typedb.bat' for TypeDB Cluster

binary/BUILD
Depend on Java 11 in APT package for consistency with TypeDB Server
Depend on `openjdk-11-jre` for APT installations.
=> Upgrade Java dependency for APT package

.grabl/automation.yml, dependencies/vaticle/repositories.bzl
Make APT package that we deploy installable again
Use Python 3.7 version to run `deploy-apt-*` jobs to avoid bazelbuild/rules_pkg#397
=> Fix APT package deployment

yaml/Yaml.java
To be able to append to and update a YAML object, we modify our wrapper Yaml class to allow mutations. This effectively copies a `Yaml` object that Snakeyaml loads, into native Java objects.
* Specialise the types in the Yaml wrapper to be either Map, List, or primitives String, Float, Int, or Boolean
* Allow loading a Yaml string or file with the new top-level API: `load`
=> Make yaml wrapper class mutable

yaml/Yaml.java
We find and protect against a previously illegal state, where the value of a Yaml map or a list element is null. We now throw an explicit exception when this scenario is encountered.
* Throw meaningful error message if given a null value in a yaml map or yaml list
=> Throw if given null values in yaml lists or maps

binary/typedb, binary/typedb.bat
As of https://github.com/vaticle/typedb/pull/6473 we no longer use a properties file or logback file, since everything is handled in the server. We can remove references to either of these from the bat and bash runner scripts.
* Remove references to Logback and Properties files in bat and bash script
=> Remove logback or typedb.properties references from binaries

test/server/TypeDBCoreRunner.java
We fix assembly tests in TypeDB by updating the core runner to use the new arguments required by TypeDB. 
- change `--port` to `--server.address`, and `--data` to `--storage.data`
=> Use new core argument format for core runner

test/Runner.java, test/server/TypeDBClusterRunner.java, test/server/TypeDBCoreRunner.java, test/server/TypeDBRunner.java
The Cluster test runner supports the latest version of TypeDB Cluster.
Additionally, the runner can be configured more flexibly, allowing for any server parameters to be overridden.
1. Support the latest TypeDB Cluster by updating how the runner boots up the server.
2. Make configuring the runner more flexible by introducing additional factory method variants.
=> Make test runner support the latest TypeDB Cluster

test/server/TypeDBClusterRunner.java, test/server/TypeDBCoreRunner.java, test/server/TypeDBRunner.java
TypeDB runner will find an unused port to boot up with to guarantee a successful bootup. In the previous approach, a random integer was chosen which could sometimes happen to be a reserved or in-use port and would cause an error when booting the server.
* replace the mechanism for choosing a port for a Core or Cluster server to boot up with:
* first, find an unused port that is not clashing and available for use
* then use this port to initialise the database
* previously, a random number was chosen that could represent a reserved/used port, cause the bootup to fail at a later stage.
* refactor the server-avaibility polling to improve readability
=> TypeDB runner allocates unused ports

test/Util.java
TypeDB Runner now handles unarchiving artifacts in a more rigorous way with respect to the provided indices. Now, we correctly check that a provided index is valid prior to an array lookup.
Prior to unarchiving a runner we need to get its path from the arguments passed to the JVM. We want to ensure that index is strictly less than args.length so that
```java
File file = new File(args[index]);
```
is valid.
We check if index is equal to args.length as well as greater than, as both will lead to the `args[index]` call to fail.
=> Fix runner archive extraction error

test/BUILD, test/Util.java, test/cluster/TypeDBClusterServerRunner.java, test/console/TypeDBConsoleRunner.java, test/core/TypeDBCoreRunner.java, test/rules.bzl
We extend TypeDB Runner to include support for tests run in Kotlin and refactor the way Runner finds passed archives for extraction and execution.
Previously, we passed core, cluster and console archive paths to the program and delineated them by their index. Now we pass them using command line argument flags leveraging picocli as we do across other repositories for similar purposes. For example, where would previously invoke
```sh
java <BazelTestRunner> <coreRunnerArchive> <consoleRunnerArchive>
```
we now invoke
```sh
java <BazelTestRunner> --server <coreRunnerArchive> --console <consoleRunnerArchive>
```
Under the previous implementation, it wasn't possible to run the console runner alone.
Additionally, we have added a rule `typedb_kt_test` which we make use of in Studio.
=> Refactor runner, adding support for kotlin

collection/Collections.java, collection/Permutations.java
We impement lazy permutation generation and a short-circuiting intersection existence check.
* create new `collections/Permutations` which contains a lazy permutation generator and a non-lazy permutation generator
* lazy permutation generator follows C++ `next_permutation` algorithm - explanation at https://stackoverflow.com/questions/352203/generating-permutations-lazily
* implement an optimised intersection existence check which doesn't require computing the entire intersection set
=> Implement lazy permutations and intersection check

.factory/automation.yml, BUILD, README.md, dependencies/vaticle/repositories.bzl
We've changed all instances of Grabl to Factory in line with the change in name of our CI.
- We've renamed our `.grabl` CI config file to `.factory`.
- We've replaced all references to grabl.io with factory.vaticle.com.
- We've replaced our environment variables that use the name GRABL with ones that use FACTORY.
=> Rename Grabl to Factory

.factory/automation.yml, dependencies/vaticle/repositories.bzl
We've migrated our continuous integration for this repo to Vaticle Factory from Grabl.
We've updated:
- dependencies.
- uses of pyenv that are no longer in line with our approach.
- machine definitions from ubuntu 21.04 to 22.04.
=> Migrate to Factory

.factory/automation.yml
We've re-instated the use of pyenv in certain Factory job definitions. Removing it in favour of using the system python3 had far-reaching ramifications that proved too costly to immediately address.
We've re-instated our use of pyenv in `deploy-github`, `deploy-apt-snapshot` and `deploy-apt-release`.
=> Re-instate use of pyenv

.factory/automation.yml, deployment.bzl
We've bumped the version of python installed by pyenv to resolve a segfault when building Python 3.6.10 on our current CI machines. 
We've bumped the version of python installed by pyenv from 3.6.10 to 3.7.9.
We've also ensured we're referencing `typedb-common` as the repository as opposed to `common`.
=> Bump version of python installed by pyenv for github deployment

BUILD
Currently, we don't include the test directory files in the main jar produced by typedb-common. As raised by a community member, we should include this so other people can make use of this via the provided jars.
We've included all of the java files found under //test in the `srcs` argument to `java_library`.
We've also corrected one scary \*/\* import and now explicitly specify what directory is being brought in.
=> Include TypeDB runners in common library jar

yaml/YAML.java
The float parsing in the YAML parser has been replaced with double parsing. This is because Java attempts to parse float-like YAML strings to double and throws an error when parsing them to float, and float parsing hadn't been used anywhere so it went unnoticed. Float-like strings are now parsed as doubles.
All references to floats in the YAML class have been replaced with doubles in class names, method names, etc.
=> Changed float to double in YAML parser

binary/typedb.bat
We can now launch TypeDB from any folder in Windows (provided TypeDB has been added to the user's environment).
TypeDB also gets launched in a new window, which the user can freely close or quit via Ctrl+C without interruption once they are finished.
Fixes https://github.com/vaticle/typedb/issues/6780
Fixes https://github.com/vaticle/typedb/issues/6781
We've refactored 'typedb.bat' to use the absolute path rather than relative, allowing the command to be used from anywhere.
We've added the keyword `start` before running the server via Java. This launches the server in a new window.
=> Fix TypeDB Windows Launcher UX

test/cluster/TypeDBClusterRunner.java, test/cluster/TypeDBClusterServerRunner.java
We prevent runners from ever using each others ports or file system state by always assigning random ports for the runners and always generating a new folder (via a random UUID) for the storage.
We now find as many unused ports as necessary and create a new folder with a random UUID as a name for each runner (which may contain multiple servers).
=> Isolate runner environments

.bazelrc, test/TypeDBRunner.java, test/TypeDBSingleton.java, test/Util.java, test/cluster/ClusterServerOpts.java, test/cluster/TypeDBClusterRunner.java, test/cluster/TypeDBClusterServerRunner.java, test/core/TypeDBCoreRunner.java
We've enabled resetting and deleting the associated files for any TypeDBRunner. Resetting the Runner allows the saving of space by only deleting the state, rather than having to create a new runner.
We've also changed the Java language level to 11 for this project via Bazel.
We've added two methods to the TypeDBRunner interface: 
* `reset()`: deleting all of the state for TypeDB, essentially ensuring that on next boot a new system will be created without requiring the creation of a new runner (which involves unarchiving a distribution).
* `deleteFiles()`: deleting all of the TypeDB runner files, clearing space as needed.
We've also added a utility method `deleteDirectoryContents()`.
We've also changed the Java language arguments in .bazelrc: 
```
-java_language_version=11 …
```
=> Allow resetting and deleting the files of TypeDB Runners

util/Double.java
`Double` values should be compared approximately. We added a class `Double` with a method `equalsApproximate` for such comparison.
We added a `Double` class. 
The method `equalsApproximate` of this class compares two `double`s by their absolute error.
=> New class for approximate doubles comparison

binary/typedb, binary/typedb.bat
Updates typedb startup scripts (`typedb` and `typedb.bat`) to reflect the simplified directory structure of server/lib introduced in [typedb#6821](https://github.com/vaticle/typedb/pull/6821) 
* Updates the script to remove the switch of classpaths between ( `server/lib/{dev <--> prod}` when the --debug flag is set on mac)
* Simplifies the classpath to be `/server/lib/*` instead of `/server/lib/common/*:/server/lib/{dev,prod}/*`
=> Update typedb startup scripts to reflect simplified dependencies folder

test/Util.java
We ensure the TypeDB process spawned by the runner utility uses the same java version as the test. This avoids issues due to the runner using a different java installation from the host machine.
* Sets the `JAVA_HOME` environment variable on the `ProcessExecutor` used by TypeDB (core & enterprise) runners.
=> Ensure TypeDB processes spawned by tests use the same java installation

.factory/automation.yml, binary/BUILD
We no longer deploy `typedb-binary` as a separate package, but rather a single package called `typedb` which contains server, console, and the binary. See https://github.com/vaticle/typedb/pull/6935.
=> Remove apt deployment

binary/typedb, binary/typedb.bat, test/enterprise/TypeDBEnterpriseServerRunner.java
We provide a single `server` entry point for starting up both core and enterprise server, whichever happens to be installed. We also omit `server` or `console` from the usage help if it is not present to avoid confusion. See https://github.com/vaticle/typedb/issues/6942 for more details.
We also improve the UX of the windows version of the entry point. Console no longer opens in a new window, `--help` is printed inline as expected, and in the event of the server failure, the logs are displayed to the user.
=> Improve entry point runner UX

.gitattributes, BUILD, binary/typedb.bat
When launching the server, a bug caused additional output that claimed a batch label that did exist, didn't. We've corrected the line endings from LF to CRLF on TypeDB's batch launcher.
As above.
* Changed the line endings on typedb.bat.
* Added a gitattributes file to specify the above requirement for bat files for the future. 
* Added checkstyle for the above new file.
* Added an end of line and fixed a space.
The line endings change seems to be invisible to git and GitHub's changes viewer. To verify this change, checkout and run `cat -ev binary/typedb.bat` to see the new line endings.
=> Fix line endings for TypeDB batch launcher

.factory/automation.yml, BUILD, WORKSPACE, dependencies/vaticle/repositories.bzl
Updates artifact deployment & consumption rules to use cloudsmith instead of the self-hosted sonatype repository.
* Updates deployment rules to point to Cloudsmith
=> Migrate artifact hosting to cloudsmith 
