vaticle/typedb-common

- WORKSPACE
- dependencies/graknlabs/dependencies.bzl
Recent upgrade to Python 3 broke our CI.
- Use updated `@graknlabs_build_tools`
- Use updated imports from `@rules_python`
> Fix CI issues related to Python upgrade

- .circleci/config.yml
- dependencies/graknlabs/dependencies.bzl
Use Ubuntu 16 image and update build tools
> Use Ubuntu 16 image and update build tools

- BUILD
- WORKSPACE
In order for keeping codebase clean and maintainable, extraneous dependencies should not be present `WORKSPACE`
Remove loading external repos that are not needed
> Cleanup WORKSPACE file from extraneous load statements

- BUILD
- util/Objects.java
To give us a convenient, minimal expressive string representation of any class that can be used in both client-java and Grakn Core
Add Objects.className
> Add Objects.className

- README.md
- dependencies/graknlabs/repositories.bzl
To delete our license from README
> Delete license from README

- binary/grakn
To allow Grakn to be more talkative in debug mode
Add a flag to the Grakn shell script that makes logback more talkative if the --debug flag is set.
> Make Grakn use debug logback config in debug mode

- concurrent/actor/Actor.java
- concurrent/actor/eventloop/Promise.java
In cluster, we have did a simplification that removes most of the usage of actors, therefore many actor and promise APIs are not being used anymore. This PR brings actor up to date with the latest version of actor in cluster.
> Simplify actor and promise API

- concurrent/actor/Actor.java
- concurrent/actor/eventloop/EventLoop.java
Currently, there is a major limitation in the Actor library such that an unhandled exception in an actor instance would be swallowed by the event loop.
This PR adds the functionality allowing actors to be notified of the exception that it failed to handle. This would allow actors to decide on whether to recover (if said actor considers the exception non-fatal) or shut down (if it considers the exception fatal).
```
class MyActor extends Actor<MyActor> {
@Override
public void exception(Exception e) {
// handle the uncaught exception
}
}
```
This PR depends on: https://github.com/graknlabs/common/pull/47.
> Adds the functionality to notify Actors of unhandled exceptions

- concurrent/actor/eventloop/EventLoop.java
- concurrent/actor/eventloop/LogicalTimerQueue.java
We have implemented error handling in `ScheduledJob`. It now takes an exception handler during construction which will be invoked in case of failure.
This PR is a follow up on https://github.com/graknlabs/common/pull/48
> Implement error handling for EventLoop's ScheduledJob

- .grabl/automation.yml
To fix the build in graknlabs:master
Add config:version-candidate to automation.yml
> Add config:version-candidate to automation.yml

- .grabl/automation.yml
Grabl recently changed the `automation.yml` syntax to have `image` instead of `machine`
Replace all `machine:` usages with `image:`
> Adapt to new Grabl

- binary/grakn
- binary/grakn.bat
We've upgraded both `grakn` and `grakn.bat`, removing environment variables that no longer needs to be supplied.
- Remove `GRAKN_DAEMON_JAVAOPTS` and `STORAGE_JAVAOPTS`
> Update bootup scripts

- test/server/GraknCoreRunner.java
In order to allow us running grakn server (through runner) in debug mode, we add constructors to allow grakn runner to run with `--debug` flag.
Add parameter to pass in `--debug` flag to grakn runner.
> Add debug option to grakn runner

- .grabl/automation.yml
Recently we added the support for background `monitor` script. Therefore we change the foreground job script from `script` to `command`.
> Update grabl automation yaml syntax 

- binary/grakn.bat
Make `grakn.bat` operational with Grakn 2.0 Server and Console
Drop first argument (either `server` or `console`) when passing to Grakn's Java process.
> Fix Grakn binary script for Windows

- test/server/BUILD
- test/server/GraknClusterRunner.java
- test/server/GraknCoreRunner.java
- test/server/GraknRunner.java
- test/server/GraknRunnerBase.java
- test/server/rules.bzl
We have added a Grakn Cluster implementation of `GraknRunner` which will allow running a single node Grakn Cluster.
- Created a base runner implementation `GraknRunnerBase`
- Created `GraknCoreRunner` and `GraknClusterRunner`
> Add a new GraknRunner implementation for Grakn Cluster

- binary/grakn
Fix `grakn` binary script to be operational again 
Check whether `server` and `console` directories exist in `$GRAKN_HOME` directory (instead of current directory)
> Fix binary script

- test/BUILD
- test/Runner.java
- test/console/ConsoleRunner.java
- test/rules.bzl
- test/server/GraknClusterRunner.java
- test/server/GraknCoreRunner.java
- test/server/GraknRunner.java
Allow cluster in distribution to run with peer addresses.
- Allow cluster in distribution to run with peer addresses.
> Allow cluster in distribution to run with peer addresses

- test/console/ConsoleRunner.java
Allow running console without script file.
Allow running console without script file.
> Allow running console without script file

- util/Java.java
Allow detecting Java version to warn users if they're running under incompatible version.
Add `grakn.common.util.Java.getMajorVersion` to detect Java runtime version.
> Add utility class to detect Java version

- BUILD
- WORKSPACE
- dependencies/graknlabs/repositories.bzl
- dependencies/maven/artifacts.snapshot
Use updated `assemble_maven` to assemble deployed JARs
Upgrade `@graknlabs_dependencies` and use newest `assemble_maven` rule
> Update Maven assembly rule

- collection/Collections.java
Add an implementation of a fast set intersection check based on Navigable sets to `//collection`
* Implement a fast set intersection check in `//collections:Collections.java`
> Add fast navigable set intersection

- collection/Collections.java
We add the `intersection` and `permutations` helper methods to `//collection`
* Add `permutations(List)` for generating all `n!` permutations of the list ordering
* Add `intersection(Set, Set)` which returns the intersection of the two sets
> Add collections helper methods

- collection/Collections.java
Eliminate the development branch which we do not require in this repository.
* Include #131  into master
> Remove development branch

- .factory/automation.yml
- BUILD
- dependencies/vaticle/repositories.bzl
We update dependencies so that we use the latest version of the release notes creation tool.
> Update release notes tool

- test/cluster/TypeDBClusterRunner.java
- test/core/TypeDBCoreRunner.java
We change the default host from 127.0.0.1 to localhost.
> Use localhost instead of 127.0.0.1 as server address in runner

- BUILD
- dependencies/maven/artifacts.snapshot
- dependencies/vaticle/repositories.bzl
- test/BUILD
- test/rules.bzl
Instead of enumerating all possible platforms and artifacts in these rules, we now require the user to provide the mapping from platforms to artifacts.
> Generalize native TypeDB Java tests and artifacts 
